### ISSUE TITLE
installing error.

### ISSUE THREAD

**Issue by MaximkaSha** [CERT-Polska/n6#36]
Hello. 
I was not able to install n6.
Specs:
Ubuntu Server 20.4
Docker version 20.10.8, build 3967b7d
docker-compose version 1.25.0, build unknown
git version 2.25.1
Python 3.8.10
Python 2.7.18

What I did.
Cloned git repository. While trying to build occured errors but images were built:

max@n6vm:~/n6/n6$ sudo docker images | grep n6
n6_worker     latest           539acd3d1c38   13 minutes ago      1.33GB
n6_base       latest           39c0850d1e87   13 minutes ago      1.32GB
n6_web        latest           ac3041e66f9c   About an hour ago   1.55GB
n6_mysql      latest           6579790207c2   4 hours ago         551MB
n6_rabbit     latest           aa653aa5a1c9   4 hours ago         250MB

I cant access admin page (4444/org) or any other n6 pages. But can access everything else, like rabbit or using n6 exec commands.
Intstall log in attachments
[log_int.txt](https://github.com/CERT-Polska/n6/files/7278017/log_int.txt)

**Comment by zuo** [comment]
A new version, 3.0.0, will be released soon. Hopefully, after this release, the problem won't be present.

**Comment by olekstomek** [comment]
> A new version, 3.0.0, will be released soon. Hopefully, after this release, the problem won't be present.

Probably to close.
https://github.com/CERT-Polska/n6/releases/tag/v3.0.0
https://github.com/CERT-Polska/n6/releases/tag/v3.0.1

**Comment by zuo** [comment]
This particular problem with installing should not occur after releasing the aforementioned versions 3.0.0 and 3.0.1.

Moreover, an upgrade to a new version, 3.12.0-beta2, was made recently.

So I close this ticket. If any problem with installation occurs, please do not hesitate to create a new issue.
